# -*- coding: utf-8 -*-
from django.conf.urls import *
from django.conf import settings
from django.contrib.auth.views import login, logout
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
	url(r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
	(r'^test/$', 'bc.views.Test'),
    (r'^$', 'bc.views.ShowMain'),
	(r'^add/$', 'bc.views.AddNode'),
	(r'^arms/$', 'bc.views.AllArms'),
	(r'^eco/$', 'bc.views.AllArms'),
	(r'^myeco/$', 'bc.views.Eco_ka'),
	(r'^ttc/$', 'bc.views.ShowTtc'),
	(r'^ttc/(?P<type_coal>[a-z_]+)$', 'bc.views.Change_Coal'),
	(r'^ttc_show/$', 'bc.views.Ttc'),
	(r'^kill/$', 'bc.views.Kill'),
	(r'^checked_state/$', 'bc.views.Checked_state'),
	(r'^currenttag/$', 'bc.views.CurrentTag'),
	(r'^current_ka/$', 'bc.views.CurrentKa'),
	(r'^current_bu/$', 'bc.views.CurrentBu'),
	(r'^current_tg/$', 'bc.views.CurrentTg'),
	(r'^current_cw/$', 'bc.views.CurrentCw'),
	(r'^protect_state/$', 'bc.views.ProtectState'),
	(r'^protect/$', 'bc.views.Protect'),
	(r'^bu_scheme_show/$', 'bc.views.BuSchemeShow'),
	(r'^bu_scheme/$', 'bc.views.ShowBuScheme'),
	(r'^get_tag_by_shortname/$', 'bc.views.GetTagByShortname'),
	(r'^get_tag_by_shortname_tec1/$', 'bc.views.GetTagByShortnameTec1'),
	(r'^current_values_for_report/$', 'bc.views.CurrentValuesForReport'),
	(r'^current_values_for_graph/(?P<tagid>[a-z0-9]+)$', 'bc.views.CurrentValuesForGraph'),
	(r'^current_values_for_graph_autoupdate/(?P<tagid>[a-z0-9]+)$', 'bc.views.CurrentValuesForGraphAutoupdate'),
	(r'^current_tec2/$', 'bc.views.CurrentTec2'),
	(r'^settings/$', 'bc.views.ShowSettings'),
    (r'^drags/(?P<tagid>[a-z0-9]+)$', 'bc.views.ShowDrags'),
    (r'^drags/$', 'bc.views.Drags'),
    (r'^sorted/$', 'bc.views.Sorted'),
    (r'^reports/$', 'bc.views.AddReports'),
	(r'^gettags/$', 'bc.views.GetTags'),
	(r'^errors/$', 'bc.views.Errors'),
	(r'^show_errors/$', 'bc.views.ShowErrors'),
    (r'^tag/groups/(?P<tid>[a-z0-9]+)$', 'bc.views.Groups'),
    (r'^groups/(?P<group>[a-z0-9]+)$', 'bc.views.CurrGroup'),
    (r'^arm/(?P<armid>[a-z0-9]+)$', 'bc.views.CurrArm'),
    (r'^reports/(?P<reportid>[a-z0-9]+)$', 'bc.views.EditReport'),
    (r'^reports_curr/(?P<reportid>[a-z0-9]+)$', 'bc.views.EditReportCurr'),
    (r'^reports_summ/(?P<reportid>[a-z0-9]+)$', 'bc.views.DateRangeReport'),
    (r'^for_select/(?P<parentid>[a-z0-9]+)$', 'bc.views.SelectChildren'),
    (r'^arms/(?P<armid>[a-z0-9]+)$', 'bc.views.Arms'),
    (r'^arch/(?P<device>[a-z0-9]+)$', 'bc.views.Arch'),
    (r'^value/(?P<device>[a-z0-9]+)$', 'bc.views.Value'),
    (r'^wvalue/(?P<device>[a-z0-9]+)$', 'bc.views.wValue'),
    (r'^eco/(?P<ecoid>[a-z0-9-,]+)$', 'bc.views.Ecos'),
    (r'^buses/(?P<busid>[a-z0-9]+)$', 'bc.views.Buses'),
	(r'^mydata/$', 'bc.views.MyData'),
	(r'^add/(?P<parent>[a-z0-9]+)$', 'bc.views.AddNode'),
	(r'^edit/(?P<target>[a-z0-9]+)$', 'bc.views.EditNode'),
	(r'^clone/(?P<target>[a-z0-9]+)$', 'bc.views.CloneNode'),
	url(r'^admin/', include(admin.site.urls)),
	(r'^login/$',  login, {'template_name':'login.html'}),
    (r'^logout/$', logout, {'template_name':'logout.html', 'next_page':'/'}),
    (r'^graph/$', 'bc.views.ShowGraph'),
    (r'^graph/data$', 'bc.views.GraphData'),
    (r'^graph/help$', 'bc.views.GraphHelp'),
#    (r'^admin/jsi18n/', 'django.views.i18n'),
#    (r'^static/admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
#    (r'^admin/jsi18n/', 'bc.i18n.javascript_catalog'),
#    (r'^admin/jsi18n/', 'django.views.i18n.javascript_catalog'),
)
